### ISSUE TITLE
Performance problems with Kivitendo container

### ISSUE THREAD

**Issue by pwFoo** [drnoa/kivitendo_docker#1]
Hi,

is the container (apache / postgres) optimized to run Kivitendo? Is FastCGI used?
Don't know if it's a problem with my hardware, but I don't think so...

Regards

**Comment by drnoa** [comment]
Hi pwFoo

Actually it is not really optimized and not using FastCGI, but I will try to integrate this. 
At the moment I dont have the time to do the integration, but you can integrate the FastCGI support directly in the Docker File and the apache conf. 

Regards

**Comment by rschaerer** [comment]
Hi @drnoa 

:heart: Thank you very much for maintaining a docker setup for kivitendo AND having such a nice readme! :100: 

:information_source: I intend to switch to a docker installation of kivitendo by myself soon.

:question: Is it still true that this issue is open or did you switch to FastCGI already?

And if so, what else needs to be done to run this docker setup as a container in production? Maybe I can catch up from there and contribute to this repository when I'm starting to work on deploying kivitendo with docker.

Cheers
Roger

**Comment by drnoa** [comment]
Hi @rschaerer 

your welcome and thank your for having a closer look at my project.

I am sorry I was not active maintaining the project the last months, so it is still without FastCGI upon now. But maybe over Christmas I have some time to try again. :-)
If you like you can try it yourself an maybe make a pull request?

in my opinion for a production environment it would be the best to separate the database and the application into two containers. And there is no backup, so you have to do this outside the container upon now. And last but not least I did not a lot to make the docker container secure for production. So the container is still using root to run the application.

**Comment by rschaerer** [comment]
Thanks for your blazing fast reply and the update about this project.

This will help me to get things going when I give your repo a try. But this will be beginning next year the earliest.

Enjoy the Christmas season and if you're having fun to hack on this feel free, otherwise I might dig into it when I start playing with it

**Comment by drnoa** [comment]
So now i was able to update the project to fastCGI and i integrated Kivitendo CRM as well. Give it a try and let me know if you see any improvements
